include:
  - project: mars-toolkit/gitlab-ci-helpers
    ref: release/v1-stable
    file: /build/gitlab-ci.template.yml

variables:
  ROS_VERSION: melodic

image: ros:${ROS_VERSION}-ros-base

roslint:
  stage: Test
  script:
    - apt-get update
    - apt-get install ros-${ROS_VERSION}-roslint
    - source /opt/ros/${ROS_VERSION}/setup.bash
    - mkdir -p /catkin_ws/src
    - ln -s $(pwd) /catkin_ws/src/${CI_PROJECT_NAME}
    - cd /catkin_ws/src
    - catkin_init_workspace
    - cd ..
    - catkin_make
    - catkin_make roslint

Build melodic image:
  extends: .Build image with Kaniko
  variables:
    KANIKO_DOCKERFILE: ${CI_PROJECT_DIR}/Dockerfile
    KANIKO_DESTINATION: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-melodic;${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-melodic
    KANIKO_ADDITIONAL_ARGS: --build-arg ros_distro=melodic
  except:
    - master

Build melodic image on master:
  extends: .Build image with Kaniko
  variables:
    KANIKO_DOCKERFILE: ${CI_PROJECT_DIR}/Dockerfile
    KANIKO_DESTINATION: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-melodic;${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-melodic;${CI_REGISTRY_IMAGE}:melodic
    KANIKO_ADDITIONAL_ARGS: --build-arg ros_distro=melodic
  only:
    - master

Build kinetic image:
  extends: .Build image with Kaniko
  variables:
    KANIKO_DOCKERFILE: ${CI_PROJECT_DIR}/Dockerfile
    KANIKO_DESTINATION: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-kinetic;${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-kinetic
    KANIKO_ADDITIONAL_ARGS: --build-arg ros_distro=kinetic
  except:
    - master

Build kinetic image on master:
  extends: .Build image with Kaniko
  variables:
    KANIKO_DOCKERFILE: ${CI_PROJECT_DIR}/Dockerfile
    KANIKO_DESTINATION: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-kinetic;${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-kinetic;${CI_REGISTRY_IMAGE}:kinetic
    KANIKO_ADDITIONAL_ARGS: --build-arg ros_distro=kinetic
  only:
    - master
