variables:
  ROS_VERSION: melodic

image: ros:${ROS_VERSION}-ros-base

stages:
  - Test
  - Release

roslint:
  stage: Test
  script:
    - apt-get update
    - apt-get install ros-${ROS_VERSION}-roslint
    - source /opt/ros/${ROS_VERSION}/setup.bash
    - mkdir -p /catkin_ws/src
    - ln -s $(pwd) /catkin_ws/src/${CI_PROJECT_NAME}
    - cd /catkin_ws/src
    - catkin_init_workspace
    - cd ..
    - catkin_make
    - catkin_make roslint
  needs: []

Release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(\.[0-9]+)*(-.*)?$/'
  script:
    - "true"
  release:
    name: 'Slocum Glider $CI_COMMIT_TAG'
    description: 'Slcoum Glider ROS package $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
