include:
  - project: mars-toolkit/gitlab-ci-helpers
    ref: release/v1-stable
    file: /build/gitlab-ci.template.yml

variables:
  ROS_VERSION: melodic

image: ros:${ROS_VERSION}-ros-base

roslint:
  stage: Test
  script:
    - apt-get update
    - apt-get install ros-${ROS_VERSION}-roslint
    - source /opt/ros/${ROS_VERSION}/setup.bash
    - mkdir -p /catkin_ws/src
    - ln -s $(pwd) /catkin_ws/src/${CI_PROJECT_NAME}
    - cd /catkin_ws/src
    - catkin_init_workspace
    - cd ..
    - catkin_make
    - catkin_make roslint

##############################################################################
# Docker images
##############################################################################

.Build image dind:
  extends: .Shell
  image: docker:19.03
  stage: Build Docker images
  services:
    - docker:19.03-dind
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-$ROS_DISTRO-$ARCH || true
    - docker pull ${CI_REGISTRY_IMAGE}:$ROS_DISTRO-$ARCH || true
    - |
      docker build \
             --build-arg ros_distro=$ROS_DISTRO \
             --cache-from ${CI_REGISTRY_IMAGE}:$ROS_DISTRO-$ARCH \
             --cache-from ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-$ROS_DISTRO-$ARCH \
             -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-$ROS_DISTRO-$ARCH \
             -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-$ROS_DISTRO-$ARCH \
             .
    - |
      [ "$CI_COMMIT_REF_SLUG" != "master" ] || docker build --build-arg ros_distro=$ROS_DISTRO \
                                                            --cache-from ${CI_REGISTRY_IMAGE}:$ROS_DISTRO-$ARCH \
                                                            --cache-from ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-$ROS_DISTRO-$ARCH \
                                                            -t ${CI_REGISTRY_IMAGE}:$ROS_DISTRO-$ARCH \
                                                            .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-$ROS_DISTRO-$ARCH
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-$ROS_DISTRO-$ARCH

    - |
      [ "$CI_COMMIT_REF_SLUG" != "master" ] || docker push ${CI_REGISTRY_IMAGE}:$ROS_DISTRO-$ARCH

Build melodic image - amd64:
  extends: .Build image dind
  variables:
    ARCH: amd64
    ROS_DISTRO: melodic
  tags:
    - dind

Build melodic image - arm64:
  extends: .Build image dind
  variables:
    ARCH: arm64
    ROS_DISTRO: melodic
  tags:
    - arm64
    - dind
