variables:
  ROS_VERSION: melodic

image: ros:${ROS_VERSION}-ros-base

stages:
  - Test
  - Build images
  - Build image manifests
  - Release

roslint:
  stage: Test
  script:
    - apt-get update
    - apt-get install ros-${ROS_VERSION}-roslint
    - source /opt/ros/${ROS_VERSION}/setup.bash
    - mkdir -p /catkin_ws/src
    - ln -s $(pwd) /catkin_ws/src/${CI_PROJECT_NAME}
    - cd /catkin_ws/src
    - catkin_init_workspace
    - cd ..
    - catkin_make
    - catkin_make roslint
  needs: []

.Build arch image - kaniko:
  stage: Build images
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    IMAGE_NAME: $CI_PROJECT_NAME
  script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor "--context=$CI_PROJECT_DIR" "--dockerfile=$DOCKERFILE" --cache=true --cache-repo="$CI_REGISTRY_IMAGE/kaniko" --destination "$CI_REGISTRY_IMAGE/tmp/$IMAGE_NAME-${ARCH?}:$CI_PIPELINE_IID"

Build kitchensink image - amd64:
  extends: .Build arch image - kaniko
  variables:
    ARCH: amd64
    DOCKERFILE: docker/Dockerfile

Build kitchensink image - arm64:
  extends: .Build arch image - kaniko
  variables:
    ARCH: arm64
    DOCKERFILE: docker/Dockerfile
  tags:
    - arm64

.Build manifest:
  stage: Build image manifests
  image: alpine:latest
  script:
    - curl -fsSL https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64 > /tmp/manifest-tool
    - chmod +x /tmp/manifest-tool
    - mv /tmp/manifest-tool /usr/local/bin/manifest-tool
    - |
      manifest-tool --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" \
                    push from-args \
                    --platforms linux/amd64,linux/arm64 \
                    --template $CI_REGISTRY_IMAGE/tmp/$IMAGE_NAME-ARCH:$CI_PIPELINE_IID \
                    --target $CI_REGISTRY_IMAGE/$IMAGE_NAME:$TAG

Build kitchensink sha manifest:
  extends: .Build manifest
  variables:
    IMAGE_NAME: $CI_RPOJECT_NAME
    TAG: $CI_COMMIT_SHORT_SHA

Build kitchensink branch manifest:
  extends: .Build manifest
  variables:
    IMAGE_NAME: $CI_RPOJECT_NAME
    TAG: $CI_COMMIT_REF_NAME

Release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(\.[0-9]+)*(-.*)?$/'
  script:
    - "true"
  release:
    name: 'Slocum Glider $CI_COMMIT_TAG'
    description: 'Slocum Glider ROS package $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
