include:
  - project: mars-toolkit/gitlab-ci-helpers
    ref: release/v1-stable
    file: /build/gitlab-ci.template.yml

variables:
  ROS_VERSION: melodic

image: ros:${ROS_VERSION}-ros-base

stages:
  - Build
  - Build Docker images
  - Build Docker manifests
  - Test

roslint:
  stage: Test
  script:
    - apt-get update
    - apt-get install ros-${ROS_VERSION}-roslint
    - source /opt/ros/${ROS_VERSION}/setup.bash
    - mkdir -p /catkin_ws/src
    - ln -s $(pwd) /catkin_ws/src/${CI_PROJECT_NAME}
    - cd /catkin_ws/src
    - catkin_init_workspace
    - cd ..
    - catkin_make
    - catkin_make roslint
  needs: []


.Build catkin_ws:
  extends: .Shell with cache
  stage: Build
  image: ros:$ROS_VERSION-ros-base
  script:
    - apt-get update
    - source /opt/ros/$ROS_VERSION/setup.bash
    - mkdir -p /catkin_ws/src
    - cd /catkin_ws/src
    - catkin_init_workspace
    - cd ..
    - catkin_make
    - ln -s $CI_PROJECT_DIR /catkin_ws/src/$CI_PROJECT_NAME
    - rosdep install --from-paths src --ignore-src -r -y
    - catkin_make
    - catkin_make install -DCMAKE_INSTALL_PREFIX=/opt/ros/slocum_glider_overlay
    - cp -a /opt/ros/slocum_glider_overlay $CI_PROJECT_DIR/slocum_glider_overlay
  artifacts:
    paths:
      - slocum_glider_overlay
  needs: []

amd64:melodic:Build:
  extends: .Build catkin_ws
  variables:
    ROS_VERSION: melodic

arm64:melodic:Build:
  extends: .Build catkin_ws
  variables:
    ROS_VERSION: melodic
  tags:
    - arm64

##############################################################################
# Docker images
##############################################################################

.Build image dind:
  extends: .Shell
  image: docker:19.03
  stage: Build Docker images
  services:
    - docker:19.03-dind
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull ros:$ROS_DISTRO-ros-base
    - docker pull ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-$ROS_DISTRO-$ARCH || true
    - docker pull ${CI_REGISTRY_IMAGE}:$ROS_DISTRO-$ARCH || true
    - |
      docker build \
             --build-arg ros_distro=$ROS_DISTRO \
             --cache-from ${CI_REGISTRY_IMAGE}:$ROS_DISTRO-$ARCH \
             --cache-from ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-$ROS_DISTRO-$ARCH \
             -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-$ROS_DISTRO-$ARCH \
             -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-$ROS_DISTRO-$ARCH \
             -f Dockerfile.runtime \
             .
    - |
      [ "$CI_COMMIT_REF_SLUG" != "master" ] || docker build --build-arg ros_distro=$ROS_DISTRO \
                                                            --cache-from ${CI_REGISTRY_IMAGE}:$ROS_DISTRO-$ARCH \
                                                            --cache-from ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-$ROS_DISTRO-$ARCH \
                                                            -t ${CI_REGISTRY_IMAGE}:$ROS_DISTRO-$ARCH \
                                                            -f Dockerfile.runtime \
                                                            .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-$ROS_DISTRO-$ARCH
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-$ROS_DISTRO-$ARCH
    - |
      [ "$CI_COMMIT_REF_SLUG" != "master" ] || docker push ${CI_REGISTRY_IMAGE}:$ROS_DISTRO-$ARCH
    - docker inspect --format='{{index .RepoDigests 0}}' ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-$ROS_DISTRO-$ARCH > $ROS_DISTRO-$ARCH-image-digest.txt
  artifacts:
    paths:
      - $ROS_DISTRO-$ARCH-image-digest.txt

Build melodic image - amd64:
  extends: .Build image dind
  variables:
    ARCH: amd64
    ROS_DISTRO: melodic
  tags:
    - dind
  needs:
    - amd64:melodic:Build

Build melodic image - arm64:
  extends: .Build image dind
  variables:
    ARCH: arm64
    ROS_DISTRO: melodic
  tags:
    - arm64-dind
  needs:
    - arm64:melodic:Build

##############################################################################
# Manifests
##############################################################################

.Generate image manifest:
  extends: .Shell
  image: docker:19.03
  stage: Build Docker manifests
  services:
    - docker:19.03-dind
  variables:
    DOCKER_CLI_EXPERIMENTAL: enabled
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - |
      docker manifest create ${CI_REGISTRY_IMAGE}:$TAG \
                             "$(cat "$ROS_DISTRO-amd64-image-digest.txt")" \
                             "$(cat "$ROS_DISTRO-arm64-image-digest.txt")"
    - docker manifest push ${CI_REGISTRY_IMAGE}:$TAG
  tags:
    - dind

Build melodic sha manifest:
  extends: .Generate image manifest
  variables:
    ROS_DISTRO: melodic
    TAG: $CI_COMMIT_SHA-melodic
  needs:
    - Build melodic image - amd64
    - Build melodic image - arm64


Build melodic slug manifest:
  extends: .Generate image manifest
  variables:
    ROS_DISTRO: melodic
    TAG: $CI_COMMIT_REF_SLUG-melodic
  needs:
    - Build melodic image - amd64
    - Build melodic image - arm64

Build melodic manifest:
  extends: .Generate image manifest
  variables:
    ROS_DISTRO: melodic
    TAG: melodic
  needs:
    - Build melodic image - amd64
    - Build melodic image - arm64
  only:
    - master
