variables:
  ROS_VERSION: melodic

image: ros:${ROS_VERSION}-ros-base

stages:
  - Test
  - Build images
  - Build image manifests
  - Release

roslint:
  stage: Test
  script:
    - apt-get update
    - apt-get install ros-${ROS_VERSION}-roslint
    - source /opt/ros/${ROS_VERSION}/setup.bash
    - mkdir -p /catkin_ws/src
    - ln -s $(pwd) /catkin_ws/src/${CI_PROJECT_NAME}
    - cd /catkin_ws/src
    - catkin_init_workspace
    - cd ..
    - catkin_make
    - catkin_make roslint
  needs: []

.Build arch image - dind:
  stage: Build images
  image: docker:19.03
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03-dind
  before_script:
    - docker info
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" || true
    - docker pull "$CI_REGISTRY_IMAGE:$CI_DEFAULT_BRANCH" || true
    - docker build --cache-from "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" --cache-from "$CI_REGISTRY_IMAGE:$CI_DEFAULT_BRANCH" -t "$CI_REGISTRY_IMAGE/${ARCH?}/$CI_PROJECT_NAME:$CI_PIPELINE_IID" .
    - docker push "$CI_REGISTRY_IMAGE/${ARCH?}/$CI_PROJECT_NAME:$CI_PIPELINE_IID"

Build amd64 image:
  extends: .Build arch image - dind
  variables:
    ARCH: amd64

Build arm64 image:
  extends: .Build arch image - dind
  variables:
    ARCH: arm64v8
  tags:
    - arm64-dind

Build image manifest:
  stage: Build image manifests
  image: docker:19.03
  environment:
    name: GitLab Docker registry
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_CLI_EXPERIMENTAL: "enabled"
  services:
    - docker:19.03-dind
  before_script:
    - docker info
  script:
    - docker manifest create "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE/amd64/$CI_PROJECT_NAME:$CI_PIPELINE_IID" "$CI_REGISTRY_IMAGE/arm64v8/$CI_PROJECT_NAME:$CI_PIPELINE_IID"
    - docker manifest create "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE/amd64/$CI_PROJECT_NAME:$CI_PIPELINE_IID" "$CI_REGISTRY_IMAGE/arm64v8/$CI_PROJECT_NAME:$CI_PIPELINE_IID"
    - docker manifest push -p "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker manifest push -p "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  resource_group: docker_reg


Release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(\.[0-9]+)*(-.*)?$/'
  script:
    - "true"
  release:
    name: 'Slocum Glider $CI_COMMIT_TAG'
    description: 'Slocum Glider ROS package $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
