# An override file to use local glider_hybrid_whoi repo for Gazebo.
# Without this overwride, docker-compose up will use the image
#  of Docker Hub which is from master branch of the repo.

services:
  gazebo:
    image: glider_hybrid_whoi:latest
    build:
      context: ../glider_hybrid_whoi
      dockerfile: docker/Dockerfile