MODE_UNSET = -1
MODE_IGNORE = 99

BPUMP_MODE_SPEED_CONTROL = 0
BPUMP_MODE_RELATIVE = 1
BPUMP_MODE_ABSOLUTE = 2
BPUMP_MODE_ABSOLUTE_SURFACE = 3

HEADING_MODE_HEADING = 1
HEADING_MODE_FIN = 4

PITCH_MODE_BATT_POS = 1
PITCH_MODE_PITCH_ONCE = 2
PITCH_MODE_PITCH_SERVO = 3

THRUSTER_MODE_NONE = 0
THRUSTER_MODE_PERCENT_GLIDER_VOLTAGE = 1
THRUSTER_MODE_PERCENT_THRUSTER_VOLTAGE = 2
THRUSTER_MODE_DEPTH_RATE = 3
THRUSTER_MODE_POWER = 4
