#+TITLE: Slocum Glider Sim Driver
#+AUTHOR: MIT MERS Group

This package implements a driver to interact with simulated gliders. There is
one node to simulate the glider's control system and one node to provide an
interface similar to a Dockserver or direct Freewave console.

This package is used to interface with a Gazebo simulation of the Slocum glider
implemented by the [[https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/][=glider_hybrid_whoi=]] package.

* Nodes
  This package contains two nodes: =slocum_glider_extctl_sim= and
  =slocum_glider_sim_console=.

** =slocum_glider_extctl_sim=

   In addition to implementing the extctl interface and interfacing with the
   simulator, this node publishes console output to the =console= topic and
   accepts commands on the =console_cmd= topic.

   This node currently requires all files needed to operate the glider to be
   located on a local file system (see the documentation in the node script for
   how to set the expected location). This includes:

   + =masterdata.mi= :: To determine what sensors are available and what their
     default values are.
   + =flight/config/autoexec.mi= :: To set glider specific values on startup.
   + =science/config/extctl.ini= :: To set what sensors are advertised over the
     extctl interface.
   + =flight/missions/*.mi= :: The mission files to execute.

** =slcoum_glider_sim_console=

   This node attempts to replicate an experiance like you would have connecting
   to the serial terminal on real hardware. It interacts with the sim driver
   over the =console= and =console_cmd= topics.

   Press =Ctrl-D= to close the console.

* Example Glider Files

  Example Glider files for a simulated glider (named bear) are located in the
  =example_gliders= folder.
