# Goal
#
# Yo in such a way that the glider attempts to stay within [min_altitude,
# max_altitude] from the sea floor. The commanded depth will stay within
# [min_depth, max_depth]. The behavior will abort if a depth band of
# min_depth_band cannot be maintained.

float64 min_depth
float64 max_depth
float64 min_altitude
float64 max_altitude
float64 min_depth_band

bool use_altimeter
---
# Result
---
# Feedback
