#+TITLE: Slocum Glider Serial Interface
#+AUTHOR: MIT MERS Group

This package contains a single node: =slocum_glider_serial_driver=. This
node opens a serial port and communicates with the glider, performing a variety
of tasks. As serial ports are scarce within the glider/backseat driver combo,
this node implements several independent features for communicating over this
serial port.

The following configuration applies to all features of this node:

+ =~serial_port/device= :: String naming the path to the serial port device
  used to communicate with the glider. Defaults to null, *must* be provided.

* extctl

  The backseat driver can communicate with the extctl proglet on the glider
  science computer to transfer files, en/disable glider behaviors, and read or
  write up to 32 sensors. To use this feature, the extctl proglet must be
  enabled in the science computer's =config\proglets.dat= file. See
  [[file:config/proglets.dat][proglets.dat]] for a snippet to include that enables it.

  When communicating with the extctl proglet, all glider sensors are referenced
  by an index. This index is determined by the =config\extctl.ini= file on the
  science computer. This file is a plain text file where each line contains
  either a sensor name and units for that sensor or is the string =os= or
  =is=. The first line of the file must be =os=. Every sensor/unit pair until
  the =is= line names sensors that can be written by the backseat driver. Every
  sensor/unit pair after the =is= line names sensors the glider reports to the
  backseat driver. The index of each sensor is its position in the list, with
  valid indices ranging from 0-31. The indices do *not* reset at the =is= line.

  When this feature is enabled, this node exposes the ROS API described in the
  =slocum_glider_interface= package.

** Configuration
   The extctl feature of this node can be configured using the following
   parameters:

   + =~extctl/enabled= :: Defaults to =True=. If true, the extctl feature will
     be enabled.
   + =~extctl/auto/on_hi= :: Defaults to =True=. If true, the extctl feature
     will automatically fetch the extctl.ini file from the science computer upon
     receipt of any =HI= message.
   + =~extctl/auto/when_missing= :: Defaults to =True=. If true, the extctl
     feature will automatically fetch the extctl.ini file from the science
     computer if the =~extctl/mappings= key is not set.
   + =~extctl/mappings= :: A list of objects naming the sensors read or written
     over this interface. The index in the list corresponds to the index used to
     name the sensor over the wire. The keys of each object are =writeable=
     (bool), =name= (string), and =units= (string). This must be provided on
     node start or =~extctl/auto/when_missing= must be true.

* Serial Console

  This node allows a glider operator to connect to a serial console running on
  the backseat driver through the glider comms. In order to support this, the
  =agetty= program must be installed on the backseat driver and the user
  running the node must be root (not recommended) or have permission to execute
  agetty as root through sudo with no password needed (see
  [[file:config/sudoers.d/50-backseat-interface-agetty][50-backseat-interface-agetty]]).

** Configuration

   This feature is configured by the following parameters:

   + =~tty/enabled= :: If true, the serial terminal feature is enabled. Defaults
     to =True=.
   + =~tty/agetty= :: Command to run when launching an agetty instance. Defaults
     to ="agetty"=.
   + =~tty/auto/enabled= :: Should agetty auto log in to a user
     account. Defaults to =False=
   + =~tty/auto/username= :: The user agetty should auto log in to. Defaults to
     the user running the node.

   To trigger this feature, connect to the science computer (using =consci=) and
   run the command:

   #+begin_src shell
     u4stalk $SERIAL_PORT_NUMBER 9600
   #+end_src

   then send the sentence: =$TT*00=. If the node can start a serial console, you
   will receive =$TS,S*7f= and agetty will be started based on the configuration
   provided through the parameter server. Otherwise, you will receive the
   sentence =$TS,F*6a= and no serial terminal will be started.

   **NOTE**: While the serial console is active the backseat driver cannot send
   or receive any other messages, so use it sparingly.

   **NOTE**: While u4stalk is active the backseat driver cannot send or receive
   any messages related to the extctl feature, so use it sparingly.
