#!/usr/bin/env python

import rospy

from slocum_glider_mission_controller import GliderController

if __name__ == '__main__':
    rospy.init_node('slocum_glider_backseat_driver')

    controller = GliderController()
    controller.spin()
